### ISSUE TITLE
Soundness issue with `.map`

### ISSUE THREAD

**Issue by steffahn** [KaiJewson/try-rwlock#2]
I just noticed this crate suffers from the same kind of soundness issue [as `owning-ref` does](https://github.com/Kimundi/owning-ref-rs/issues/71). Repro:
```rs
use try_rwlock::{ReadGuard, TryRwLock};

fn main() {
    let l = TryRwLock::new(());
    let x = l.try_read().unwrap();
    let z: ReadGuard<'_, (), String>;
    {
        let s = "Hello World!".to_string();
        let s_ref: &String = &s;
        let y: ReadGuard<'_, (), &String> = ReadGuard::map(x, |_| &s_ref);
        z = ReadGuard::map(y, |s: &&String| *s);
        // s deallocated here
    }
    println!("{}", &*z); // printing garbage, accessing `s` after it’s freed
}
```

See the linked issue for more information. Possible solutions include adding a `U: 'lock` bound to `ReadGuard<'a, T, U>`, which is likely the best approach. I’m fairly certain that `WriteGuard` has the same problem, did not test it though.

**Comment by steffahn** [comment]
Nevermind, `WriteGuard` should be fine, because of the `_invariant_over_u` field giving rise to an implicit `U: 'lock` bound already.

**Comment by SabrinaJewson** [comment]
Thank you very much! It should be fixed now.

**Comment by steffahn** [comment]
Feel free to double-check, just as a sanity-check, that the code I gave really doesn't compile anymore :-)

**Comment by steffahn** [comment]
Other than that, great, and thanks for the fast response!

**Comment by SabrinaJewson** [comment]
> Feel free to double-check, just as a sanity-check, that the code I gave really doesn't compile anymore :-)

Yes, I tried it out and it failed to compile.
